import type { NextFunction, Request, RequestHandler, Response } from 'express';
import { Errors } from './errors';
import { getDimension, UNIT_TYPES, type DimensionId } from '../config/taxonomy';
import type { UnitQuery } from '../services/document.repository';

/**
 * Request plumbing: async handler wrapping, and validation of everything that arrives as a
 * string in a URL.
 *
 * Query parameters are parsed strictly rather than passed through. Filter values are checked
 * against the taxonomy, not merely trimmed — an unknown value is a client mistake worth naming,
 * and it keeps arbitrary strings from reaching a database query.
 */

/** Forwards a rejected promise to the error middleware, which Express 4 will not do itself. */
export function asyncHandler(
  handler: (req: Request, res: Response, next: NextFunction) => Promise<unknown>,
): RequestHandler {
  return (req, res, next) => {
    void handler(req, res, next).catch(next);
  };
}

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Document ids are generated by `randomUUID`, so anything else is not worth a store lookup. */
export function documentId(req: Request): string {
  const raw = req.params['id'];
  if (typeof raw !== 'string' || !UUID_PATTERN.test(raw)) {
    throw Errors.validation('That document id is not valid.');
  }
  return raw;
}

function firstValue(value: unknown): string | undefined {
  if (typeof value === 'string') return value;
  if (Array.isArray(value)) {
    const first = value[0];
    return typeof first === 'string' ? first : undefined;
  }
  return undefined;
}

/** Accepts `?sentiment=positive&sentiment=neutral` and `?sentiment=positive,neutral` alike. */
function listValues(value: unknown): string[] {
  const raw = Array.isArray(value) ? value : [value];
  const out: string[] = [];
  for (const entry of raw) {
    if (typeof entry !== 'string') continue;
    for (const piece of entry.split(',')) {
      const trimmed = piece.trim().toLowerCase().replace(/\s+/g, '_');
      if (trimmed.length > 0) out.push(trimmed);
    }
  }
  return [...new Set(out)];
}

function dimensionFilter(query: Request['query'], dimensionId: DimensionId): string[] | undefined {
  const values = listValues(query[dimensionId]);
  if (values.length === 0) return undefined;

  const dimension = getDimension(dimensionId);
  const allowed = new Set(dimension.values.map((entry) => entry.id));
  const unknown = values.filter((value) => !allowed.has(value));
  if (unknown.length > 0) {
    throw Errors.validation(`Unknown ${dimension.label.toLowerCase()} filter: ${unknown.join(', ')}.`, {
      allowed: [...allowed],
    });
  }
  return values;
}

function boundedInt(value: unknown, name: string, min: number, max: number): number | undefined {
  const raw = firstValue(value);
  if (raw === undefined || raw.trim() === '') return undefined;

  const parsed = Number.parseInt(raw, 10);
  if (!Number.isFinite(parsed) || parsed < min || parsed > max) {
    throw Errors.validation(`"${name}" must be a whole number between ${min} and ${max}.`);
  }
  return parsed;
}

function boundedFloat(value: unknown, name: string, min: number, max: number): number | undefined {
  const raw = firstValue(value);
  if (raw === undefined || raw.trim() === '') return undefined;

  const parsed = Number.parseFloat(raw);
  if (!Number.isFinite(parsed) || parsed < min || parsed > max) {
    throw Errors.validation(`"${name}" must be a number between ${min} and ${max}.`);
  }
  return parsed;
}

const MAX_SEARCH_LENGTH = 120;

/** Builds the repository query from the URL. Every field is optional; all are validated. */
export function parseUnitQuery(req: Request): Partial<UnitQuery> & Record<string, unknown> {
  const query = req.query;

  const sentiment = dimensionFilter(query, 'sentiment');
  const emotion = dimensionFilter(query, 'emotion');
  const contentType = dimensionFilter(query, 'contentType');
  const topic = dimensionFilter(query, 'topic');

  const unitTypeValues = listValues(query['unitType']);
  const allowedUnitTypes = new Set(UNIT_TYPES.map((entry) => entry.id as string));
  const unknownUnitTypes = unitTypeValues.filter((value) => !allowedUnitTypes.has(value));
  if (unknownUnitTypes.length > 0) {
    throw Errors.validation(`Unknown passage type filter: ${unknownUnitTypes.join(', ')}.`, {
      allowed: [...allowedUnitTypes],
    });
  }

  const sourceRaw = firstValue(query['source']);
  if (sourceRaw !== undefined && sourceRaw !== '' && sourceRaw !== 'ai' && sourceRaw !== 'heuristic') {
    throw Errors.validation('"source" must be either "ai" or "heuristic".');
  }

  const search = firstValue(query['search'])?.trim();
  if (search !== undefined && search.length > MAX_SEARCH_LENGTH) {
    throw Errors.validation(`Search text must be ${MAX_SEARCH_LENGTH} characters or fewer.`);
  }

  const section = firstValue(query['section'])?.trim();

  return {
    page: boundedInt(query['page'], 'page', 1, 100_000) ?? 1,
    pageSize: boundedInt(query['pageSize'], 'pageSize', 1, 200) ?? 50,
    ...(sentiment ? { sentiment } : {}),
    ...(emotion ? { emotion } : {}),
    ...(contentType ? { contentType } : {}),
    ...(topic ? { topic } : {}),
    ...(unitTypeValues.length > 0 ? { unitType: unitTypeValues } : {}),
    ...(boundedInt(query['documentPage'], 'documentPage', 1, 100_000) !== undefined
      ? { documentPage: boundedInt(query['documentPage'], 'documentPage', 1, 100_000) }
      : {}),
    ...(section ? { section } : {}),
    ...(search ? { search } : {}),
    ...(boundedFloat(query['minConfidence'], 'minConfidence', 0, 1) !== undefined
      ? { minConfidence: boundedFloat(query['minConfidence'], 'minConfidence', 0, 1) }
      : {}),
    ...(sourceRaw === 'ai' || sourceRaw === 'heuristic' ? { source: sourceRaw } : {}),
  };
}

export function parsePagination(req: Request, defaultLimit = 20, maxLimit = 100): { limit: number; offset: number } {
  return {
    limit: boundedInt(req.query['limit'], 'limit', 1, maxLimit) ?? defaultLimit,
    offset: boundedInt(req.query['offset'], 'offset', 0, 1_000_000) ?? 0,
  };
}

/**
 * A `Content-Disposition` value that cannot break out of its own header. Non-ASCII filenames are
 * carried by the RFC 5987 `filename*` parameter and given a plain ASCII fallback.
 */
export function contentDisposition(filename: string): string {
  const ascii = filename.replace(/[^\x20-\x7e]/g, '_').replace(/["\\]/g, '_');
  return `attachment; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(filename)}`;
}